/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.0-RC10
 * Generated at: 2014-01-31 14:39:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.util.ArrayList;
import org.apache.commons.jrcs.diff.Chunk;
import org.apache.commons.jrcs.diff.Delta;
import org.apache.commons.jrcs.diff.Diff;
import org.apache.commons.jrcs.diff.Revision;
import org.opensolaris.opengrok.analysis.AnalyzerGuru;
import org.opensolaris.opengrok.analysis.FileAnalyzer.Genre;
import org.opensolaris.opengrok.web.DiffData;
import org.opensolaris.opengrok.web.DiffType;
import java.io.File;
import java.io.IOException;
import org.opensolaris.opengrok.configuration.Project;
import org.opensolaris.opengrok.history.HistoryGuru;
import org.opensolaris.opengrok.web.EftarFileReader;
import org.opensolaris.opengrok.web.PageConfig;
import org.opensolaris.opengrok.web.Prefix;
import org.opensolaris.opengrok.web.Util;
import org.opensolaris.opengrok.Info;
import org.opensolaris.opengrok.web.PageConfig;
import org.opensolaris.opengrok.web.PageConfig;
import java.util.EnumSet;
import org.opensolaris.opengrok.web.PageConfig;
import org.opensolaris.opengrok.web.Prefix;

public final class diff_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {


private String getAnnotateRevision(DiffData data) {
    if (data.type == DiffType.OLD || data.type == DiffType.NEW) {
        return "<script type=\"text/javascript\">/* <![CDATA[ */ "
            + "document.rev = 'r=" + data.rev[data.type == DiffType.NEW ? 1 : 0]
            + "'; /* ]]> */</script>";
    }
    return "";
}


    private PageConfig cfg;
    /** Just cleanup cached objects */

    public void jspDestroy() {
        if (cfg != null) {
            cfg.cleanup();
        }
    }


/* ---------------------- foot.jspf members start --------------------- */
    private static EnumSet<Prefix> needAddDiv = EnumSet.of(
        Prefix.HIST_L, Prefix.XREF_P, Prefix.DIFF_P, Prefix.MORE_P,
        // could NOT find any mapping/reference to those ones:
        Prefix.HIST_S, Prefix.XREF_S, Prefix.DIFF_S, Prefix.MORE_S);
/* ---------------------- foot.jspf members end --------------------- */

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/pageheader.jspf", Long.valueOf(1331040730000L));
    _jspx_dependants.put("/foot.jspf", Long.valueOf(1331040730000L));
    _jspx_dependants.put("/mast.jsp", Long.valueOf(1331040730000L));
    _jspx_dependants.put("/pageconfig.jspf", Long.valueOf(1331040730000L));
    _jspx_dependants.put("/httpheader.jspf", Long.valueOf(1331040730000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error.jsp", false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;


/* ---------------------- mast.jsp start --------------------- */
{
    cfg = PageConfig.get(request);
    String redir = cfg.canProcess();
    if (redir == null || redir.length() > 0) {
        if (redir == null) {
            response.sendError(HttpServletResponse.SC_NOT_FOUND);
        } else {
            response.sendRedirect(redir);
        }
        return;
    }
    // jel: hmmm - questionable for dynamic content
    long flast = cfg.getLastModified();
    if (request.getDateHeader("If-Modified-Since") >= flast) {
        response.setStatus(HttpServletResponse.SC_NOT_MODIFIED);
        return;
    }
    response.setDateHeader("Last-Modified", flast);

    // Use UTF-8 if no encoding is specified in the request
    if (request.getCharacterEncoding() == null) {
        request.setCharacterEncoding("UTF-8");
    }

    // set the default page title
    String path = cfg.getPath();
    cfg.setTitle("Cross Reference: " + path);

    String context = request.getContextPath();
    cfg.getEnv().setUrlPrefix(context + Prefix.SEARCH_R + "?");

    String uriEncodedPath = cfg.getUriEncodedPath();
    String rev = cfg.getRequestedRevision();


/* ---------------------- httpheader.jsp start --------------------- */
{
    cfg = PageConfig.get(request);
    String styleDir = cfg.getCssDir();
    String ctxPath = request.getContextPath();
    String dstyle = styleDir + '/' + "style.css";
    String pstyle = styleDir + '/' + "print.css";

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n");
      out.write("    \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\" xml:lang=\"en\" lang=\"en\">\n");
      out.write("<head>\n");
      out.write("<meta name=\"robots\" content=\"noindex,nofollow\" />\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("<meta name=\"generator\" content=\"");
      out.print(Info.getVersion());
      out.write(' ');
      out.write('(');
      out.print(Info.getRevision());
      out.write(")\" />\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=8\" />\n");
      out.write("<link rel=\"icon\" href=\"");
      out.print(styleDir);
      out.write("/img/icon.png\" type=\"image/png\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" media=\"all\"\n");
      out.write("    title=\"Default\" href=\"");
      out.print( dstyle );
      out.write("\" />\n");
      out.write("<link rel=\"alternate stylesheet\" type=\"text/css\" media=\"all\"\n");
      out.write("    title=\"Paper White\" href=\"");
      out.print( pstyle );
      out.write("\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(styleDir);
      out.write("/print.css\" media=\"print\" />\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.print(styleDir);
      out.write("/jquery.tooltip.css\" />\n");
      out.write("\n");
      out.write("<link rel=\"search\" href=\"");
      out.print(ctxPath);
      out.write("/opensearch\"\n");
      out.write("    type=\"application/opensearchdescription+xml\"\n");
      out.write("    title=\"OpenGrok Search for current project(s)\" />\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath);
      out.write("/jquery-1.4.4.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath);
      out.write("/jquery.tooltip-1.3.pack.js\"></script>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctxPath);
      out.write("/utils.js\"></script>\n");
      out.write("<title>");
      out.print(cfg.getTitle());
      out.write("</title>");

    out.write(cfg.getHeaderData());

      out.write("\n");
      out.write("</head>");

}
/* ---------------------- httpheader.jsp end --------------------- */

      out.write("<body>\n");
      out.write("<script type=\"text/javascript\">/* <![CDATA[ */\n");
      out.write("    document.hash = '");
      out.print( cfg.getDocumentHash()
    );
      out.write("';document.rev = '");
      out.print( rev
    );
      out.write("';document.link = '");
      out.print( context + Prefix.XREF_P + uriEncodedPath
    );
      out.write("';document.annotate = ");
      out.print( cfg.annotate() );
      out.write(";\n");
      out.write("    document.domReady.push(function() {domReadyMast();});\n");
      out.write("    document.pageReady.push(function() { pageReadyMast();});\n");
      out.write("/* ]]> */</script>\n");
      out.write("<div id=\"page\">\n");
      out.write("    <div id=\"whole_header\">\n");
      out.write("        <form action=\"");
      out.print( context + Prefix.SEARCH_P );
      out.write("\">\n");
      out.write("<div id=\"header\">");
 
/* ---------------------- pageheader.jspf start --------------------- */
{
    cfg = PageConfig.get(request);

      out.write("\n");
      out.write("<a href=\"");
      out.print( request.getContextPath() );
      out.write("/\"><span id=\"MastheadLogo\"></span></a>\n");
      out.print( cfg.getEnv().getConfiguration().getHeaderIncludeFileContent() );
      out.write('\n');
 
}
/* ---------------------- pageheader.jspf end --------------------- */

      out.write('\n');
      out.write("\n");
      out.write("    <div id=\"pagetitle\"><span id=\"filename\"\n");
      out.write("                    >Cross Reference: ");
      out.print( cfg.getCrossFilename() );
      out.write("</span>");

    String dtag = cfg.getDefineTagsIndex();
    if (dtag.length() > 0) {
                    
      out.write("<br/>");
      out.print( dtag );

    }
    
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<div id=\"Masthead\">\n");
      out.write("    <tt><a href=\"");
      out.print( context + Prefix.XREF_P );
      out.write("/\">xref</a>: ");
      out.print( Util
        .breadcrumbPath(context + Prefix.XREF_P, path,'/',"",true,cfg.isDir())
    );
      out.write("</tt>\n");
      out.write("</div>\n");
      out.write("<div id=\"bar\">\n");
      out.write("    <ul>\n");
      out.write("        <li><a href=\"");
      out.print( context );
      out.write("/\"><span id=\"home\"></span>Home</a></li>");

    if (!cfg.hasHistory()) {
        
      out.write("<li><span id=\"history\"></span><span class=\"c\">History</span></li>");

    } else {
        
      out.write("<li><a href=\"");
      out.print( context + Prefix.HIST_L + uriEncodedPath
            );
      out.write("\"><span id=\"history\"></span>History</a></li>");

    }
    if (!cfg.hasAnnotations() /* || cfg.getPrefix() == Prefix.HIST_S */ ) {
        
      out.write("<li><span class=\"c\"><span class=\"annotate\"></span>Annotate</span></li>");

    } else if (cfg.annotate()) {
        
      out.write("<li><span id=\"toggle-annotate-by-javascript\" style=\"display: none\"><a\n");
      out.write("            href=\"#\" onclick=\"javascript:toggle_annotations(); return false;\"\n");
      out.write("            title=\"Show or hide line annotation(commit revisions,authors).\"\n");
      out.write("            ><span class=\"annotate\"></span>Annotate</a></span><span\n");
      out.write("            id=\"toggle-annotate\"><a href=\"");
      out.print(
                context + Prefix.XREF_P + uriEncodedPath
                + (rev.length() == 0 ? "" : "?") + rev
            );
      out.write("\"><span class=\"annotate\"></span>Annotate</a></span></li>");

    } else {
        
      out.write("<li><a href=\"#\" onclick=\"javascript:get_annotations(); return false;\"\n");
      out.write("            ><span class=\"annotate\"></span>Annotate</a></li>");

    }
    if (!cfg.isDir()) {
        if (cfg.getPrefix() == Prefix.XREF_P) {
        
      out.write("<li><a href=\"#\" onclick=\"javascript:lntoggle();return false;\"\n");
      out.write("            title=\"");
      out.print( "Show or hide line numbers (might be slower if "
                + "file has more than 10 000 lines)."
            );
      out.write("\"><span id=\"line\"></span>Line#</a></li><li><a\n");
      out.write("            href=\"#\" onclick=\"javascript:lsttoggle();return false;\"\n");
      out.write("            title=\"Show or hide symbol list.\">");
      out.write("<span id=\"defbox\"></span>Navigate</a></li>");

        }
        
      out.write("<li><a href=\"");
      out.print( context + Prefix.RAW_P + uriEncodedPath
            + (rev.length() == 0 ? "" : "?") + rev
            );
      out.write("\"><span id=\"download\"></span>Download</a></li>");

    }
        
      out.write("<li><input type=\"text\" id=\"search\" name=\"q\" class=\"q\" />\n");
      out.write("            <input type=\"submit\" value=\"Search\" class=\"submit\" /></li>");

    Project proj = cfg.getProject();
    String[] vals = cfg.getSearchOnlyIn();
        
      out.write("<li><input type=\"checkbox\" name=\"path\" value=\"");
      out.print( vals[0]
            );
      out.write('"');
      out.write(' ');
      out.print( vals[2] );
      out.write("/> only in <b>");
      out.print( vals[1] );
      out.write("</b></li>\n");
      out.write("        ");
      out.write("\n");
      out.write("    </ul>");

    if (proj != null) {
    
      out.write("\n");
      out.write("    <input type=\"hidden\" name=\"project\" value=\"");
      out.print(proj.getDescription());
      out.write("\" />");

    }

      out.write("\n");
      out.write("</div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("<div id=\"content\">\n");

}
/* ---------------------- mast.jsp end --------------------- */


/* ---------------------- diff.jsp start --------------------- */
{
    cfg = PageConfig.get(request);
    DiffData data = cfg.getDiffData();

    if (data.errorMsg != null)  {


      out.write("\n");
      out.write("<div class=\"src\">\n");
      out.write("    <h3 class=\"error\">Error:</h3>\n");
      out.write("    <p>");
      out.print( data.errorMsg );
      out.write("</p>\n");
      out.write("</div>");


    } else if (data.genre == Genre.IMAGE) {

        String link = request.getContextPath() + Prefix.RAW_P
            + Util.htmlize(cfg.getPath());

      out.write("\n");
      out.write("<div id=\"difftable\">\n");
      out.write("    <table class=\"image\">\n");
      out.write("        <thead>\n");
      out.write("        <tr><th>");
      out.print( data.filename );
      out.write(" (revision ");
      out.print( data.rev[0] );
      out.write(")</th>\n");
      out.write("            <th>");
      out.print( data.filename );
      out.write(" (revision ");
      out.print( data.rev[1] );
      out.write(")</th>\n");
      out.write("        </tr>\n");
      out.write("        </thead>\n");
      out.write("        <tbody>\n");
      out.write("        <tr><td><img src=\"");
      out.print( link );
      out.write('?');
      out.write('r');
      out.write('=');
      out.print( data.rev[0] );
      out.write("\"/></td>\n");
      out.write("            <td><img src=\"");
      out.print( link );
      out.write('?');
      out.write('r');
      out.write('=');
      out.print( data.rev[1] );
      out.write("\"/></td>\n");
      out.write("        </tr>\n");
      out.write("        </tbody>\n");
      out.write("    </table>\n");
      out.write("</div>");


    } else if (data.genre != Genre.PLAIN && data.genre != Genre.HTML) {

        String link = request.getContextPath() + Prefix.RAW_P
            + Util.htmlize(cfg.getPath());

      out.write("\n");
      out.write("<div id=\"src\">Diffs for binary files cannot be displayed! Files are <a\n");
      out.write("    href=\"");
      out.print( link );
      out.write('?');
      out.write('r');
      out.write('=');
      out.print( data.rev[0] );
      out.write('"');
      out.write('>');
      out.print(
        data.filename );
      out.write("(revision ");
      out.print( data.rev[0] );
      out.write(")</a> and <a\n");
      out.write("    href=\"");
      out.print( link );
      out.write('?');
      out.write('r');
      out.write('=');
      out.print( data.rev[1] );
      out.write('"');
      out.write('>');
      out.print(
        data.filename );
      out.write("(revision ");
      out.print( data.rev[1] );
      out.write(")</a>.\n");
      out.write("</div>");


    } else if (data.revision.size() == 0) {
        
      out.write("\n");
      out.write("        ");
      out.print( getAnnotateRevision(data) );
      out.write("\n");
      out.write("        <b>No differences found!</b>");


    } else {
        //-------- Do THE DIFFS ------------
        int ln1 = 0;
        int ln2 = 0;
        String rp1 = data.param[0];
        String rp2 = data.param[1];
        String reqURI = request.getRequestURI();
        String[] file1 = data.file[0];
        String[] file2 = data.file[1];

        DiffType type = data.type;
        boolean full = data.full;

      out.write('\n');
      out.print( getAnnotateRevision(data) );
      out.write("\n");
      out.write("<div id=\"diffbar\">\n");
      out.write("    <div class=\"legend\">\n");
      out.write("        <span class=\"d\">Deleted</span>\n");
      out.write("        <span class=\"a\">Added</span>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"tabs\">");

        for (DiffType t : DiffType.values()) {
            if (type == t) {
        
      out.write(" <span class=\"active\">");
      out.print( t.toString() );

                if (t == DiffType.OLD) {
            
      out.write("  ( ");
      out.print( data.rev[0] );
      out.write(' ');
      out.write(')');

                } else if (t == DiffType.NEW) {
            
      out.write("  ( ");
      out.print( data.rev[1] );
      out.write(' ');
      out.write(')');

                }
            
      out.write("</span>");

            } else {
        
      out.write(" <span><a href=\"");
      out.print( reqURI );
      out.write("?r1=");
      out.print( rp1 );
      out.write("&amp;r2=");
      out.print( rp2
            );
      out.write("&amp;format=");
      out.print( t.getAbbrev() );
      out.write("&amp;full=");
      out.print( full ? '1' : '0'
            );
      out.write('"');
      out.write('>');
      out.print( t.toString() );

                if (t == DiffType.OLD) {
            
      out.write("  ( ");
      out.print( data.rev[0] );
      out.write(' ');
      out.write(')');

                } else if (t == DiffType.NEW) {
            
      out.write("  ( ");
      out.print( data.rev[1] );
      out.write(' ');
      out.write(')');

                }
            
      out.write("</a></span>");

            }
        }
    
      out.write("</div>\n");
      out.write("    <div class=\"ctype\">");

        if (!full) {
        
      out.write("\n");
      out.write("        <span><a href=\"");
      out.print( reqURI );
      out.write("?r1=");
      out.print( rp1 );
      out.write("&amp;r2=");
      out.print( rp2
            );
      out.write("&amp;format=");
      out.print( type.getAbbrev() );
      out.write("&amp;full=1\">full</a></span>\n");
      out.write("        <span class=\"active\">compact</span>");

        } else {
        
      out.write("\n");
      out.write("        <span class=\"active\">full</span>\n");
      out.write("        <span> <a href=\"");
      out.print( reqURI );
      out.write("?r1=");
      out.print( rp1 );
      out.write("&amp;r2=");
      out.print( rp2
            );
      out.write("&amp;format=");
      out.print( type.getAbbrev() );
      out.write("&amp;full=0\">compact</a></span>");

        }
    
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div id=\"difftable\">\n");
      out.write("    <div class=\"pre\">");

        if (type == DiffType.SIDEBYSIDE || type == DiffType.UNIFIED) {
        
      out.write("<table class=\"plain\">");

            if (type == DiffType.SIDEBYSIDE) {
            
      out.write("\n");
      out.write("            <thead><tr>\n");
      out.write("                <th>");
      out.print( data.filename );
      out.write(' ');
      out.write('(');
      out.print( data.rev[0] );
      out.write(")</th>\n");
      out.write("                <th>");
      out.print( data.filename );
      out.write(' ');
      out.write('(');
      out.print( data.rev[1] );
      out.write(")</th>\n");
      out.write("            </tr></thead>");

            }
            
      out.write("\n");
      out.write("            <tbody>");

        }

        for (int i=0; i < data.revision.size(); i++) {
            Delta d = data.revision.getDelta(i);
            if (type == DiffType.TEXT) {
        
      out.print( Util.htmlize(d.toString()) );

            } else {
                Chunk c1 = d.getOriginal();
                Chunk c2 = d.getRevised();
                int cn1 = c1.first();
                int cl1 = c1.last();
                int cn2 = c2.first();
                int cl2 = c2.last();

                int i1 = cn1, i2 = cn2;
                StringBuilder bl1 = new StringBuilder(80);
                StringBuilder bl2 = new StringBuilder(80);
                for (; i1 <= cl1 && i2 <= cl2; i1++, i2++) {
                    Util.htmlize(file1[i1], bl1);
                    Util.htmlize(file2[i2], bl2);
                    String[] ss = Util.diffline(bl1, bl2);
                    file1[i1] = ss[0];
                    file2[i2] = ss[1];
                    bl1.setLength(0);
                    bl2.setLength(0);
                }
                // deleted
                for (; i1 <= cl1; i1++) {
                    bl1.setLength(0);
                    bl1.append("<span class=\"d\">");
                    Util.htmlize(file1[i1], bl1);
                    file1[i1] = bl1.append("</span>").toString();
                }
                // added
                for (; i2 <= cl2; i2++) {
                    bl2.setLength(0);
                    bl2.append("<span class=\"a\">");
                    Util.htmlize(file2[i2], bl2);
                    file2[i2] = bl2.append("</span>").toString();
                }

                if (type == DiffType.UNIFIED) {
// UDIFF
                    if (cn1 > ln1 || cn2 > ln2) {
            
      out.write("\n");
      out.write("            <tr class=\"k\"><td>");

                        if (full || (cn2 - ln2 < 20)) {
                            for (int j = ln2; j < cn2; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln2 );
      out.write("</i>");
      out.print(
                    Util.htmlize(file2[j]) );
      out.write("<br/>");

                            }
                        } else {
                            for (int j = ln2; j < ln2 + 8; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print(
                    Util.htmlize(file2[j]) );
      out.write("<br/>");

                            }
                
      out.write("<br/>--- <b>");
      out.print( cn2 - ln2 - 16
                    );
      out.write(" unchanged lines hidden</b> (<a href=\"");
      out.print( reqURI
                    );
      out.write("?r1=");
      out.print( rp1 );
      out.write("&amp;r2=");
      out.print( rp2
                    );
      out.write("&amp;format=");
      out.print( type.getAbbrev()
                    );
      out.write("&amp;full=1#");
      out.print( ln2 );
      out.write("\">view full</a>) --- <br/><br/>");

                            ln2 = cn2 - 8;
                            for (int j = ln2; j < cn2; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln2 );
      out.write("</i>");
      out.print( Util.htmlize(file2[j]) );
      out.write("<br/>");

                            }
                        }
                
      out.write("</td>\n");
      out.write("            </tr>");

                        ln1 = cn1;
                    }
                    if (cn1 <= cl1) {
            
      out.write("\n");
      out.write("            <tr><td>");

                        for (int j = cn1; j  <= cl1 ; j++) {
                
      out.write("<del class=\"d\">");
      out.print( ++ln1 );
      out.write("</del>");
      out.print( file1[j]
                );
      out.write("<br/>");

                        }
                
      out.write("</td>\n");
      out.write("            </tr>");

                    }
                    if (cn2 <= cl2) {
            
      out.write("\n");
      out.write("            <tr class=\"k\"><td>");

                        for (int j = cn2; j  < cl2; j++) {
                
      out.write("<i class=\"a\">");
      out.print( ++ln2 );
      out.write("</i>");
      out.print( file2[j]
                );
      out.write("<br/>");

                        }
                
      out.write("<i class=\"a\">");
      out.print( ++ln2 );
      out.write("</i>");
      out.print( file2[cl2] );

                        if(full) {
                
      out.write("<a name=\"");
      out.print( ln2 );
      out.write("\" />");

                        }
                
      out.write("</td>\n");
      out.write("            </tr>");

                    }
                } else if (type == DiffType.SIDEBYSIDE) {
// SDIFF
                    if (cn1 > ln1 || cn2 > ln2) {
            
      out.write("\n");
      out.write("            <tr class=\"k\"><td>");

                        if (full || cn2 - ln2 < 20) {
                            for (int j = ln1; j < cn1; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln1 );
      out.write("</i>");
      out.print(
                    Util.htmlize(file1[j]) );
      out.write("<br/>");

                            }
                
      out.write("</td><td>");

                            for (int j = ln2; j  < cn2 ; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln2 );
      out.write("</i>");
      out.print(
                    Util.htmlize(file2[j]) );
      out.write("<br/>");

                            }
                        } else {
                            for (int j = ln1; j < ln1 + 8; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print(
                    Util.htmlize(file1[j]) );
      out.write("<br/>");

                            }
                
      out.write("<br/>--- <b>");
      out.print( cn1 - ln1 - 16
                    );
      out.write(" unchanged lines hidden</b> (<a href=\"");
      out.print( reqURI
                    );
      out.write("?r1=");
      out.print( rp1 );
      out.write("&amp;r2=");
      out.print( rp2
                    );
      out.write("&amp;format=");
      out.print( type.getAbbrev()
                    );
      out.write("&amp;full=1#");
      out.print( ln2 );
      out.write("\">view full</a>) --- <br/><br/>");

                            ln1 = cn1 - 8;
                            for (int j = ln1; j < cn1; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln1 );
      out.write("</i>");
      out.print(
                    Util.htmlize(file1[j]) );
      out.write("<br/>");

                            }
                
      out.write("</td><td>");

                            for (int j = ln2; j < ln2 + 8; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print(
                    Util.htmlize(file2[j]) );
      out.write("<br/>");

                            }
                
      out.write("<br/>--- <b>");
      out.print( cn2 - ln2 - 16
                    );
      out.write(" unchanged lines hidden</b> (<a href=\"");
      out.print( reqURI
                    );
      out.write("?r1=");
      out.print( rp1 );
      out.write("&amp;r2=");
      out.print( rp2
                    );
      out.write("&amp;format=");
      out.print( type.getAbbrev()
                    );
      out.write("&amp;full=1#");
      out.print( ln2 );
      out.write("\">view full</a>) --- <br/><br/>");

                            ln2 = cn2 - 8;
                            for (int j = ln2; j < cn2; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln2 );
      out.write("</i>");
      out.print(
                    Util.htmlize(file2[j]) );
      out.write("<br/>");

                            }
                        }
                
      out.write("</td>\n");
      out.write("            </tr>");

                    }
            
      out.write("\n");
      out.write("            <tr class=\"k\"><td>");

                    for (int j = cn1; j  <= cl1; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln1 );
      out.write("</i>");
      out.print( file1[j] );
      out.write("<br/>");

                    }
                
      out.write("</td><td>");

                    for (int j = cn2; j  <= cl2; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln2 );
      out.write("</i><a name=\"");
      out.print( ln2 );
      out.write("\"></a>");
      out.print(
                    file2[j] );
      out.write("<br/>");

                    }
                
      out.write("</td>\n");
      out.write("            </tr>");

// OLD
                } else if (type == DiffType.OLD) {
                    // OLD
                    if (cn1 > ln1) {
                        if (full || cn1 - ln1 < 20) {
                            for (int j = ln1; j < cn1; j++) {
        
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln1 );
      out.write("</i>");
      out.print(
            Util.htmlize(file1[j]) );
      out.write("<br/>");

                            }
                        } else {
                            for (int j = ln1; j < ln1 + 8; j++) {
        
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print(
            Util.htmlize(file1[j]) );
      out.write("<br/>");

                            }
        
      out.write("<br/>--- <b>");
      out.print( cn1 - ln1 - 16
            );
      out.write(" unchanged lines hidden</b> (<a href=\"");
      out.print( reqURI
            );
      out.write("?r1=");
      out.print( rp1 );
      out.write("&amp;r2=");
      out.print( rp2
            );
      out.write("&amp;format=");
      out.print( type.getAbbrev()
            );
      out.write("&amp;full=1#");
      out.print(ln1);
      out.write("\">view full</a>) --- <br/><br/>");

                            ln1 = cn1 - 8;
                            for (int j = ln1; j < cn1; j++) {
        
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln1 );
      out.write("</i>");
      out.print(
            Util.htmlize(file1[j]) );
      out.write("<br/>");

                            }
                        }
                    }
                    for (int j = cn1; j  <= cl1 ; j++) {
        
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln1 );
      out.write("</i>");
      out.print( file1[j] );
      out.write("<br/>");

                    }
                    if (full) {
        
      out.write("<a name=\"");
      out.print(ln1);
      out.write("\" ></a>");

                    }
// NEW
                } else if (type == DiffType.NEW) {
                    if (cn2 > ln2) {
                        if (full || cn2 - ln2 < 20) {
                            for (int j = ln2; j  < cn2 ; j++) {
        
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln2 );
      out.write("</i>");
      out.print(
            Util.htmlize(file2[j]) );
      out.write("<br/>");

                            }
                        } else {
                            for (int j = ln2; j < ln2 + 8; j++) {
        
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print(
            Util.htmlize(file2[j]) );
      out.write("<br/>");

                            }
        
      out.write("<br/>--- <b>");
      out.print( cn2 - ln2 - 16
            );
      out.write(" unchanged lines hidden</b> (<a href=\"");
      out.print( reqURI
            );
      out.write("?r1=");
      out.print( rp1 );
      out.write("&amp;r2=");
      out.print( rp2
            );
      out.write("&amp;format=");
      out.print( type.getAbbrev()
            );
      out.write("&amp;full=1#");
      out.print( ln2 );
      out.write("\">view full</a>) --- <br/><br/>");

                            ln2 = cn2 - 8;
                            for (int j = ln2; j < cn2; j++) {
            
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln2 );
      out.write("</i>");
      out.print(
                Util.htmlize(file2[j]) );
      out.write("<br/>");

                            }
                        }
                    }
                    for (int j = cn2; j  <= cl2 ; j++) {
        
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( ++ln2 );
      out.write("</i>");
      out.print( file2[j] );
      out.write("<br/>");

                    }
                    if (full) {
        
      out.write("<a name=\"");
      out.print( ln2 );
      out.write("\"></a>");

                    }
                }
            } // else
        } // for
// deltas done, dump the remaining
        if (file1.length >= ln1) {
            if (type == DiffType.SIDEBYSIDE) {
                if (full || file1.length - ln1 < 20) {
            
      out.write("\n");
      out.write("            <tr><td>");

                    for (int j = ln1; j < file1.length ; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print( Util.htmlize(file1[j]) );
      out.write("<br/>");

                    }
                
      out.write("</td><td>");

                    for (int j = ln2; j < file2.length ; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print( Util.htmlize(file2[j]) );
      out.write("<br/>");

                    }
                
      out.write("</td>\n");
      out.write("            </tr>\n");
      out.write("            </tbody>\n");
      out.write("        </table>");

                } else {
            
      out.write("\n");
      out.write("            <tr><td>");

                    for (int j = ln1; j < ln1 + 8 ; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print( Util.htmlize(file1[j]) );
      out.write("<br/>");

                    }
                
      out.write("<br/> --- <b>");
      out.print( file1.length - ln1 - 8
                );
      out.write(" unchanged lines hidden</b> --- </td><td>");

                    for (int j = ln2; j < ln2 + 8 ; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print( Util.htmlize(file2[j]) );
      out.write("<br/>");

                    }
                
      out.write("<br/>--- <b>");
      out.print( file1.length - ln1 - 8
                );
      out.write(" unchanged lines hidden</b> ---</td>\n");
      out.write("            </tr>\n");
      out.write("            </tbody>\n");
      out.write("        </table>");

                }
            } else if (type == DiffType.UNIFIED) {
                if (full || file2.length - ln2 < 20) {
            
      out.write("\n");
      out.write("            <tr><td>");

                    for (int j = ln2; j < file2.length ; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print( Util.htmlize(file2[j]) );
      out.write("<br/>");

                    }
                
      out.write("</td>\n");
      out.write("            </tr>\n");
      out.write("            </tbody>\n");
      out.write("        </table>");

                } else {
            
      out.write("\n");
      out.write("            <tr><td>");

                    for (int j = ln2; j < ln2 + 8 ; j++) {
                
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print( Util.htmlize(file2[j]) );
      out.write("<br/>");

                    }
                
      out.write("<br/>--- <b>");
      out.print( file2.length - ln2 - 8
                );
      out.write(" unchanged lines hidden</b> ---</td>\n");
      out.write("            </tr>\n");
      out.write("            </tbody>\n");
      out.write("        </table>");

                }
            } else if (type == DiffType.OLD) {
                if (full || file1.length - ln1 < 20) {
                    for (int j = ln1; j < file1.length ; j++) {
        
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print( Util.htmlize(file1[j]) );
      out.write("<br/>");

                    }
                } else {
                    for (int j = ln1; j < ln1 + 8 ; j++) {
        
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print( Util.htmlize(file1[j]) );
      out.write("<br/>");

                    }
        
      out.write("<br/> --- <b>");
      out.print( file1.length - ln1 - 8
        );
      out.write(" unchanged lines hidden</b> ---<br/>");

                }
            } else if (type == DiffType.NEW) {
                if (full || file2.length - ln2 < 20) {
                    for (int j = ln2; j < file2.length ; j++) {
        
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print(Util.htmlize(file2[j]));
      out.write("<br/>");

                    }
                } else {
                    for (int j = ln2; j < ln2 + 8 ; j++) {
        
      out.write('<');
      out.write('i');
      out.write('>');
      out.print( j+1 );
      out.write("</i>");
      out.print( Util.htmlize(file2[j]) );
      out.write("<br/>");

                    }
        
      out.write("<br/> --- <b>");
      out.print( file2.length - ln2 - 8
        );
      out.write(" unchanged lines hidden</b> ---<br/>");

                }
            }
        }

//----DIFFS Done--------
    
      out.write("</div>\n");
      out.write("</div>");

    }
}
/* ---------------------- diff.jsp end --------------------- */


/* ---------------------- foot.jspf start --------------------- */
{
    cfg = PageConfig.get(request);

        
      out.write("\n");
      out.write("    <div id=\"footer\">\n");
      out.write("<p><a href=\"http://www.opensolaris.org/os/project/opengrok/\"\n");
      out.write(" title=\"Served by OpenGrok\"><span id=\"fti\"></span></a></p>\n");
      out.write("<p>Indexes created ");
      out.print( cfg.getEnv().getDateForLastIndexRun() );
      out.write("</p>\n");
      out.write("    ");
      out.print( cfg.getEnv().getConfiguration().getFooterIncludeFileContent() );
      out.write("\n");
      out.write("    ");

    if (needAddDiv.contains(cfg.getPrefix())) {
        
      out.write("</div>");
 // #content
    }
    // #footer, #page:
    
      out.write("\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");

}
/* ---------------------- foot.jspf end --------------------- */

      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
